"""Item 12 — Auto startup diagnosis (port/conflict/env/db/compile)."""
class AutoDiagnose:
    CLASSES = ["PORT_CONFLICT","PORT_NOT_REACHABLE","DATABASE_UNAVAILABLE","MISSING_ENVIRONMENT_VARIABLE","DEPENDENCY_INSTALLATION_FAILURE","COMPILATION_FAILURE","RUNTIME_EXCEPTION","CONFIGURATION_FAILURE","AUTHENTICATION_FAILURE","DOCKER_FAILURE","UNKNOWN"]
